name: env
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _py-xgboost-mutex=2.0=cpu_0
  - asn1crypto=1.2.0=py37_0
  - attrs=19.3.0=py_0
  - blas=1.0=mkl
  - bokeh=1.3.4=py37_0
  - boto=2.49.0=py37_0
  - boto3=1.9.234=py_0
  - botocore=1.12.234=py_0
  - bz2file=0.98=py37_1
  - ca-certificates=2019.11.28=hecc5488_0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.11.28=py37_0
  - cffi=1.13.1=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - cryptography=2.8=py37h1ba5d50_0
  - cuda80=1.0=h205658b_0
  - cudatoolkit=8.0=3
  - cycler=0.10.0=py37_0
  - dbus=1.13.12=h746ee38_0
  - docutils=0.15.2=py37_0
  - eli5=0.10.1=py_0
  - expat=2.2.6=he6710b0_0
  - fastparquet=0.3.2=py37hdd07704_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - gensim=3.4.0=py37h14c3975_0
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.13=h23475e2_0
  - graphviz=2.40.1=h21bd128_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py37_0
  - intel-openmp=2019.4=243
  - jinja2=2.10.3=py_0
  - jmespath=0.9.4=py_0
  - joblib=0.13.2=py37_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py37he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxgboost=0.90=he1b5a44_2
  - libxml2=2.9.9=hea5a465_1
  - llvmlite=0.30.0=py37hd408876_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.1.1=py37h5429711_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.14=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numba=0.46.0=py37h962f231_0
  - numpy=1.17.2=py37haad9e8e_0
  - numpy-base=1.17.2=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1d=h516909a_0
  - packaging=19.2=py_0
  - pandas=0.25.1=py37he6710b0_0
  - pango=1.42.4=h049681c_0
  - pcre=8.43=he6710b0_0
  - pillow=6.2.0=py37h34e0f95_0
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h7b6447c_0
  - py-xgboost=0.90=py37he1b5a44_2
  - py4j=0.10.7=py_1
  - pycparser=2.19=py37_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pysocks=1.7.1=py37_0
  - pyspark=2.4.4=py_0
  - python=3.7.4=h265db76_1
  - python-dateutil=2.8.0=py37_0
  - python-graphviz=0.10.1=py_0
  - python-snappy=0.5.4=py37he6710b0_0
  - pytorch=1.0.1=py3.7_cuda8.0.61_cudnn7.1.2_2
  - pytz=2019.3=py_0
  - pyyaml=5.1.2=py37h7b6447c_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py37_0
  - s3transfer=0.2.1=py37_0
  - scikit-learn=0.21.2=py37hd81dba3_0
  - scipy=1.3.1=py37h7c811a0_0
  - setuptools=41.6.0=py37_0
  - singledispatch=3.4.0.3=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - smart_open=1.8.4=py_0
  - snappy=1.1.7=hbae5bb6_3
  - sqlite=3.30.1=h7b6447c_0
  - tabulate=0.8.3=py37_0
  - tbb=2019.8=hfd86e86_0
  - thrift=0.11.0=py37hf484d3e_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.2.2=py_3
  - tornado=6.0.3=py37h7b6447c_0
  - urllib3=1.24.2=py37_0
  - wheel=0.33.6=py37_0
  - xgboost=0.90=py37he1b5a44_2
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.9.0
    - cachetools==4.0.0
    - daemonize==2.5.0
    - filelock==3.0.12
    - google-auth==1.11.0
    - google-auth-oauthlib==0.4.1
    - grpcio==1.27.0rc1
    - guildai==0.7.0rc4
    - markdown==3.1.1
    - oauthlib==3.1.0
    - pkginfo==1.5.0.1
    - protobuf==3.11.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scikit-optimize==0.5.2
    - tabview==1.4.4
    - tensorboard==2.1.0
    - virtualenv==16.7.9
    - werkzeug==0.16.0
